#!/bin/bash
set -e
set -u

for asm in `dirname $0`/fixtures/*.asm; do
  echo " => $asm"
  echo "asm -> mid"
  pokemid $asm $asm.mid
  echo "mid -> asm"
  pokemid $asm.mid $asm.new.asm
  rm $asm.mid
  rm $asm.new.asm
done
